fix(preflight): check the system default NFS version in mount config
longhorn/cli pull request #129
Opened 2024-11-25 14:50 UTC by COLDTURNIP

#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#9830

#### What this PR does / why we need it:

Though the node supports NFSv4, the NFS client picks the protocol version by `Defaultvers` defined in nfsmount.conf. This may cause problem while using backup-related features.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-11-26 01:11 UTC, derekbit commented on pkg/local/preflight/checker.go
> +	for kernelConfigScanner.Scan() {
We already check `/etc/nfsmount.conf` instead, so the check of `/boot/config-<version` can be removed. WDYT? @COLDTURNIP @mantissahz

2024-11-26 01:14 UTC, derekbit commented on pkg/local/preflight/checker.go
> +					isDefaultV4 = val == "4"
Can we list v4.2, v4.1 and v4.0's enablement?

2024-11-26 04:26 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +					isDefaultV4 = val == "4"
Sure, will add the minor version check.

2024-11-26 04:30 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +	for kernelConfigScanner.Scan() {
Maybe we still need this to ensure the NFS version capability of the kernel. The `Defaultvers` in `nfsmount.conf` defines the preferred protocol version, but it still needs to negotiate and iterate over supported versions from newer to older.

2024-11-26 04:35 UTC, derekbit commented on pkg/local/preflight/checker.go
> +	for kernelConfigScanner.Scan() {
Got it! Let's keep it. Thank you.

2024-11-26 10:35 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +
The `Defaultvers` in `/etc/nfsmount.conf` is `4` by default.

2024-11-27 00:16 UTC, c3y1huang requested changes

2024-11-27 00:16 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +	if !isKernelSupport {
It seems we could return immediately when `isKernelSupport` is determined. Any reason we will need to go through the `/etc/nfsmount.conf` check in such case?

2024-11-27 00:30 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +			return errors.Wrap(err, "failed to scan NFS mount config")
I think we can improve this by preventing validation from blocking. Instead of returning the error and terminating the progress, we could log the errors in the collection and allow the checker to proceed with other checks. What do you think?

2024-11-27 03:08 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +			return errors.Wrap(err, "failed to scan NFS mount config")
Sounds great, will append such reading errors in the final report.

2024-11-27 03:23 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +	if err == nil {
`/etc/nfsmount.conf` might be absent on some distro, and it means to keep all default settings for NFS mounts, including `Defaultvars=4` that Longhorn needs. What we want to warn the user is:

* `/etc/nfsmount.conf` presents, and
* `Defaultvars` is overridden with version other than `4.x`

2024-11-27 04:56 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +	if err == nil {
I am not sure if we are on the same page. It seems you are returning this error later any ways:
```
	if err != nil && !os.IsNotExist(err) {
		return errors.Wrap(err, "failed to check NFS default mount configurations")
	}
```
Could we simplify this by returning earlier and removing the `err == nil` condition check?

2024-11-27 06:30 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +	if err == nil {
Sure. Thanks for clarify.

2024-11-28 00:00 UTC, c3y1huang requested changes

2024-11-28 00:00 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +		}
```suggestion
	if err != nil && !os.IsNotExist(err) {
                local.collection.Log.Error = append(local.collection.Log.Error, fmt.Sprintf("Failed to check NFS default mount configurations: %v", err))
		return nil
```

2024-11-28 00:00 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +	} else {
This looks redundant. Do we need it?

2024-11-28 00:00 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +			isAllCheckPassed = false
```suggestion
			return nil
```

2024-11-28 00:00 UTC, c3y1huang commented on pkg/local/preflight/checker.go
> +			isAllCheckPassed = false
```suggestion
			return nil
```

2024-11-28 00:00 UTC, c3y1huang commented on pkg/local/preflight/checker.go
>  func (local *Checker) checkNFSv4Support() error {
I think we could remove the `error` return and instead log all errors to the collection logs. This approach could allow the checker to continue without blocking other checkups.

2024-11-28 10:08 UTC, c3y1huang commented on pkg/local/preflight/checker.go
>  func (local *Checker) checkNFSv4Support() error {
https://github.com/longhorn/longhorn/issues/9877

2024-11-28 13:31 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +		}
This part would be refactored to longhorn/go-common-libs#88 so that could be reused both in preflight and node controller.

2024-12-03 09:44 UTC, innobead commented
@COLDTURNIP if this is ready to review, re-request @c3y1huang to check this PR.

2024-12-03 13:35 UTC, COLDTURNIP commented
We're extracting some common logic between cli and LH manager. Please hold on.

2024-12-11 03:33 UTC, COLDTURNIP commented on pkg/local/preflight/checker.go
> +	local.collection.Log.Info = append(local.collection.Log.Info, "NFS4 is supported")
The test step will be covered in test plan: https://github.com/longhorn/longhorn/issues/9830#issuecomment-2530704625

2024-12-12 07:47 UTC, derekbit approved these changes
LGTM

2024-12-12 07:48 UTC, merged

2024-12-12 07:48 UTC, derekbit commented
@mergify backport v1.7.x