fix(preflight): check APT package installation by status flag
longhorn/cli pull request #132
Opened 2024-12-03 05:06 UTC by COLDTURNIP

#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#9495

#### What this PR does / why we need it:

While checking the installation status with APT package system, we should read the actual package status instead of the exit code of `dpkg-query -l` or `dpkg -l`.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-12-03 09:38 UTC, innobead requested changes

2024-12-03 09:38 UTC, innobead commented on pkg/local/preflight/packagemanager/apt.go
> +		if fields[0] == name && fields[1] == dpkgDesiredActionInstall+dpkgStatusInstalled {
Suggest removing newly created constants, as they might never be used. Just briefly explain what `ii` means reported by the command output.

```go
if fields[0] == name && fields[1] == "ii" {
```

P.S. ideally, it's better to determine if the command execution is successful by checking the exit code, if the command supports it

2024-12-03 12:47 UTC, innobead approved these changes

2024-12-03 12:47 UTC, merged

2024-12-04 05:31 UTC, COLDTURNIP commented
https://github.com/Mergifyio backport v1.7.x

2024-12-04 05:44 UTC, derekbit commented
@mergify backport v1.7.x